"""Cross-backend Ed25519 interoperability — the fleet-critical property that was previously untested.

The Stack/CI use the **cryptography** backend; comma devices ship **pycryptodome**. A device signs
its requests with pycryptodome and the Stack verifies with cryptography (and, during pairing/dev, the
reverse). If the two backends ever disagreed on a signature, EVERY device would fail to authenticate —
a total fleet auth outage. The single-backend tests in test_crypto.py cannot catch a divergence
because only one backend is active per process; this module exercises both at once.

It is skipped (not failed) when only one backend is installed, so it can't produce a false RED in a
minimal environment — but the protocol's CI installs the ``[test]`` extra (which pulls pycryptodome
alongside cryptography), so the cross-backend assertions actually RUN in CI. Run locally with both:
    /tmp/pubcore-venv/bin/python -m pytest mypilot-protocol/tests/test_crypto_interop.py
"""

from __future__ import annotations

import pytest
from mypilot_protocol import crypto

_BACKENDS = crypto._BACKENDS

pytestmark = pytest.mark.skipif(
    not ({"cryptography", "pycryptodome"} <= set(_BACKENDS)),
    reason="cross-backend interop test needs BOTH cryptography and pycryptodome installed "
    "(install the protocol's [test] extra); only one backend present here.",
)

CRY = "cryptography"
PYC = "pycryptodome"

# A few message shapes that matter on the wire: empty body, ascii, and bytes that are NOT valid
# UTF-8 (a signed request body can be arbitrary binary — qlog/video bytes), to prove signing is over
# raw bytes, not text.
_MESSAGES = [b"", b"device-auth-nonce-12345", b"\x00\xff\xfe\x80 binary body \x01\x02"]


def _b64e(raw: bytes) -> str:
    import base64

    return base64.b64encode(raw).decode("ascii")


@pytest.mark.parametrize("gen_backend", [CRY, PYC])
@pytest.mark.parametrize("msg", _MESSAGES)
def test_signatures_are_byte_identical_across_backends(gen_backend: str, msg: bytes):
    """For the SAME key+message, both backends must emit the identical RFC-8032 signature (Ed25519
    is deterministic). Byte-identity is stronger than mutual-verify and is what lets a signature
    cross the backend boundary transparently."""
    priv_raw, _pub_raw = _BACKENDS[gen_backend].gen_raw()
    priv_b64 = _b64e(priv_raw)
    sig_cry = _BACKENDS[CRY].sign_raw(priv_b64, msg)
    sig_pyc = _BACKENDS[PYC].sign_raw(priv_b64, msg)
    assert sig_cry == sig_pyc, "backends produced different signatures for the same key+message"


@pytest.mark.parametrize("msg", _MESSAGES)
def test_pycryptodome_signature_verifies_under_cryptography(msg: bytes):
    """The real fleet path: a device (pycryptodome) signs; the Stack (cryptography) verifies."""
    priv_raw, pub_raw = _BACKENDS[PYC].gen_raw()
    sig = _BACKENDS[PYC].sign_raw(_b64e(priv_raw), msg)
    assert _BACKENDS[CRY].verify_raw(_b64e(pub_raw), sig, msg) is True


@pytest.mark.parametrize("msg", _MESSAGES)
def test_cryptography_signature_verifies_under_pycryptodome(msg: bytes):
    """The reverse path (dev tooling / pairing signs on the Stack, device-side verifies)."""
    priv_raw, pub_raw = _BACKENDS[CRY].gen_raw()
    sig = _BACKENDS[CRY].sign_raw(_b64e(priv_raw), msg)
    assert _BACKENDS[PYC].verify_raw(_b64e(pub_raw), sig, msg) is True


def test_cross_backend_keys_are_interchangeable():
    """A keypair generated by one backend imports and round-trips under the other — devices and the
    Stack mint keys with different libraries but must trust each other's public keys."""
    priv_raw, pub_raw = _BACKENDS[PYC].gen_raw()
    priv_b64, pub_b64 = _b64e(priv_raw), _b64e(pub_raw)
    msg = b"key-portability-check"
    # Sign on cryptography using the pycryptodome-minted private key; verify on pycryptodome.
    sig = _BACKENDS[CRY].sign_raw(priv_b64, msg)
    assert _BACKENDS[PYC].verify_raw(pub_b64, sig, msg) is True


@pytest.mark.parametrize("verify_backend", [CRY, PYC])
@pytest.mark.parametrize("sign_backend", [CRY, PYC])
def test_tampered_message_rejected_across_backends(sign_backend: str, verify_backend: str):
    """A signature from any backend must FAIL to verify on any backend once the message is altered —
    interoperability must not weaken tamper-rejection in either direction."""
    priv_raw, pub_raw = _BACKENDS[sign_backend].gen_raw()
    sig = _BACKENDS[sign_backend].sign_raw(_b64e(priv_raw), b"original-body")
    assert _BACKENDS[verify_backend].verify_raw(_b64e(pub_raw), sig, b"original-body!") is False
